services:
  - type: web
    name: football-prediction-backend
    runtime: python
    rootDir: football-prediction-app/backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: football-prediction-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: RAPIDAPI_KEY
        sync: false  # You'll need to set this manually in Render dashboard

databases:
  - name: football-prediction-db
    databaseName: football_prediction
    user: football_user
    plan: free