services:
  # Backend API Service
  - type: web
    name: football-prediction-backend
    runtime: python
    rootDir: football-prediction-app/backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: football-prediction-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: football-prediction-redis
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: RAPIDAPI_KEY
        sync: false  # Set manually in Render dashboard
      - key: FOOTBALL_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: SPORTMONKS_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: SPORTMONKS_FALLBACK_TOKENS
        sync: false  # Set manually in Render dashboard
      - key: TOKEN_ENCRYPTION_PASSWORD
        sync: false  # Set manually in Render dashboard - use strong password
      - key: TOKEN_ENCRYPTION_SALT
        sync: false  # Set manually in Render dashboard - use unique salt
      - key: INTERNAL_API_KEYS
        generateValue: true
      - key: ENABLE_SCHEDULER
        value: false  # Disabled on main API service
      - key: CORS_ORIGINS
        value: https://football-prediction-frontend.onrender.com,https://football-prediction-frontend-zx5z.onrender.com,https://football-prediction-frontend-2cvi.onrender.com

  # Scheduler Service (Background Worker)
  - type: worker
    name: football-prediction-scheduler
    runtime: python
    rootDir: football-prediction-app/backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_scheduler.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: football-prediction-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: football-prediction-redis
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromService:
          type: web
          name: football-prediction-backend
          envVarKey: SECRET_KEY
      - key: SPORTMONKS_API_KEY
        fromService:
          type: web
          name: football-prediction-backend
          envVarKey: SPORTMONKS_API_KEY
      - key: SPORTMONKS_FALLBACK_TOKENS
        fromService:
          type: web
          name: football-prediction-backend
          envVarKey: SPORTMONKS_FALLBACK_TOKENS
      - key: TOKEN_ENCRYPTION_PASSWORD
        fromService:
          type: web
          name: football-prediction-backend
          envVarKey: TOKEN_ENCRYPTION_PASSWORD
      - key: TOKEN_ENCRYPTION_SALT
        fromService:
          type: web
          name: football-prediction-backend
          envVarKey: TOKEN_ENCRYPTION_SALT
      - key: ENABLE_SCHEDULER
        value: true
      - key: IS_SCHEDULER_INSTANCE
        value: true

  # Frontend Static Site
  - type: web
    name: football-prediction-frontend
    runtime: static
    rootDir: football-prediction-app/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://football-prediction-backend-2cvi.onrender.com
      - key: REACT_APP_SPORTMONKS_ENABLED
        value: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Redis for caching
  - type: redis
    name: football-prediction-redis
    plan: free  # Upgrade for production
    maxmemoryPolicy: allkeys-lru  # LRU eviction for cache

databases:
  - name: football-prediction-db
    databaseName: football_prediction
    user: football_user
    plan: free  # Upgrade to starter or standard for production